[package]
name = "gjson"
version = "0.1.0"
authors = ["importcjj <importcjj@gmail.com>"]
description = "JSON Parser for Rust - Get JSON values quickly"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

[dev-dependencies]
criterion = "0.2"
json = "*"
serde_json = "1.0"

[[bench]]
name = "gjson_benchmark"
harness = false