[package]
name = "pygjson"
version = "0.1.0"
authors = ["importcjj <importcjj@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pygjson"
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
gjson = { path = "../gjson" }

